<?php
class OrderConfirmationController extends OrderConfirmationControllerCore
{
    /*
    * module: sendyapimodule
    * date: 2018-06-21 11:09:07
    * version: 1.0.0
    */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $sendyapimodule = Module::getInstanceByName('sendyapimodule');
    }

    public function completeOrder(){
        $sendyapimodule = Module::getInstanceByName('sendyapimodule');
        $res = $sendyapimodule->completeOrder();
        echo $res;
    }

    public function displayOrderConfirmation($order)
    {
        $sendyapimodule = Module::getInstanceByName('sendyapimodule');
        $address = new Address($this->context->cart->id_address_delivery);
        $customer = new Customer ($order->id_customer);
        $fname = $customer->firstname;
        $lname = $customer->lastname;
        $customer_name = $fname . " " . $lname;
        $customer_phone = $address->phone;
        $customer_mail = $customer->email;

        $context = Context::getContext();
        $to_details_cookie = $context->cookie->to_details;
        $to_details = json_decode($to_details_cookie, true);
        $api_to = $to_details['to_name'];
        $to_lat = $to_details['to_lat'];
        $to_long = $to_details['to_long']; 

        $res = $sendyapimodule->getPriceQuote($api_to, $to_lat, $to_long, $customer_name, $customer_phone, $customer_mail);
        echo $res;
        $this->completeOrder();
        return Hook::exec('displayOrderConfirmation', array('order' => $order));
    }
}